import pyautogui

pyautogui.click(440,70,duration=2)
pyautogui.click(440,70)
pyautogui.click(440,70)
pyautogui.click(1500,1000,duration=2)
pyautogui.write("hello",interval=0.2)
pyautogui.press("enter")
pyautogui.write("I'm a hacker",interval=0.2)
pyautogui.press("enter")
pyautogui.write("Now let me hack this computer",interval=0.2)
pyautogui.click (90,3000)
pyautogui.write("cmd",interval=0.2)
pyautogui.press("enter")
pyautogui.click(900,500,duration=2)
pyautogui.write("color A")
pyautogui.press("enter")
pyautogui.write("tree")
pyautogui.press("enter")
pyautogui.click(1700,900,duration=2)
pyautogui.press("enter")
pyautogui.write("I've finished hacking",interval=0.2)
pyautogui.press("enter")
pyautogui.write("Hah, hah, hah",interval=0.2)